name: Nelson CI

on: [push]

jobs:

  ubuntu:
    name: Ubuntu-24.04
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Install Nelson as Snap 
        run: |
          sudo snap install nelson
          sudo snap connect nelson:home
          sudo snap connect nelson:removable-media

      - uses: actions/checkout@v5

      - name: creates artifacts directory
        run: |
          mkdir -p /home/runner/install/artifacts

      - name: build and install module
        run: |
          nelson -cli --quiet -e "nmm('install', getenv('GITHUB_WORKSPACE'));quit"

      - name: package module
        run: |
          nelson -cli --quiet -e "nmm('package', 'module_skeleton', '/home/runner/install/artifacts');quit"

      - name: run tests
        run: |
          nelson -cli --quiet -e "test_run('module_skeleton', 'all_tests', '/home/runner/install/artifacts/tests_results.xml');quit"

      - name: run benchs
        run: |
          nelson -cli --quiet -e "test_run('module_skeleton', 'benchs', '/home/runner/install/artifacts/benchs_results.xml');quit"

      - uses: actions/upload-artifact@v5
        with:
          name: module_skeleton-github-action-artifacts-linux
          path: /home/runner/install/artifacts/

  windows_64:
    name: Windows 64 bits
    runs-on: windows-2025
    timeout-minutes: 30    
    defaults:
      run:
       shell: cmd

    steps:
      - name: Download Nelson v1.15.0 (win64)
        run: |
          $null = mkdir c:/install
          (new-object net.webclient).DownloadFile("https://github.com/nelson-lang/nelson/releases/download/v1.15.0/Nelson-1.15.0.5475-x86-64.exe", "C:\install\Nelson-x86-64.exe")
        shell: powershell

      - name: Install Nelson
        run: |
          C:/install/Nelson-x86-64.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /DIR="c:/install/Nelson"

      - uses: actions/checkout@v5

      - name: creates artifacts directory
        run: |
          $null = mkdir c:/install/artifacts
        shell: powershell

      - name: build and install module
        run: |
          "c:/install/Nelson/bin/x64/nelson-adv-cli" --noipc --quiet -e "nmm('install', getenv('GITHUB_WORKSPACE'));quit"

      - name: package module
        run: |
          "c:/install/Nelson/bin/x64/nelson-adv-cli" --noipc --quiet -e "nmm('package', 'module_skeleton', 'c:/install/artifacts');quit"

      - name: run tests
        run: |
          "c:/install/Nelson/bin/x64/nelson-adv-cli" --noipc --quiet -e "test_run('module_skeleton', 'all_tests', 'c:/install/artifacts/tests_results.xml');quit"

      - name: run benchs
        run: |
          "c:/install/Nelson/bin/x64/nelson-adv-cli" --noipc --quiet -e "test_run('module_skeleton', 'benchs', 'c:/install/artifacts/benchs_results.xml');quit"

      - uses: actions/upload-artifact@v5
        with:
          name: module_skeleton-github-action-artifacts
          path: c:/install/artifacts/

